---
dependencies:
- role: pound-base
  tags:
  - pound

  pound_local_cert_dir: /tmp/ansible/ca/out
  pound_local_cert_list: "{{ client_to_manage }}"
  pound_self_signed_cert: no
  pound_listeners:
  - type: https
    port: 443
    addr: "{{ ansible_ssh_host }}"
    opts:
    - name: Cert
      type: cert
      value: "{{ pound_local_cert_list }}"
    - name: Ciphers
      type: string
      value:
      - EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4
    - name: SSLHonorCipherOrder
      value:
      - 1
    - name: Disable
      value:
      - TLSv1
  pound_backends:
  - addr: 10.0.42.11
    port: 80
  - addr: 10.0.42.12
    port: 80
  pound_backend_emergency:
    addr: 127.0.0.1
    port: 8000

