---

# Documentation:
# This playbook will install all dependencies roles. The configuration
# is sourced from roles/requirements.yml and all vendor modules are 
# installed by default into roles/vendors/. Each time this playbook is
# call, all vendor roles will be purged.


# TODO: Find a work around for task omnipotence

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    root_dir: ../
    purge: false

  roles:

    - role: ansible_get_roles
      force_purge: "{{ purge }}"
      installation_dir: roles/vendors
      installation_prefix: "{{ root_dir }}"

    - role: ansible_gen_conf
      force_purge: "{{ purge }}"
      installation_prefix: "{{ root_dir }}"

