---
# Documentation:
# This playbook helps to check if all hosts defined into the inventory
# are joinable. This playbook can also retrieve a dump of all remote
# hosts. This should support most UNIX operating systems (OSX included).


- name: Ensure Python is available on targets
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: ansible_install_python

- name: Test the connection and dump targets environment
  hosts: all
  become: false
  vars:
    dump_vars: true
  roles:
    - role: ansible_test_connection
    - role: dumpall
      when: dump_vars | bool
