---

# Include OS variables
- name: include os variables
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution|lower }}.yml"
  - default.yml


# Install varnish
- name: install varnish
  yum: name=varnish state=present

# Create directory
- name: create include directory
  file:
    path: /etc/varnish/include
    state: directory

# Push varnish parameters
- name: edit default parameters
  lineinfile:
    dest: /etc/varnish/varnish.params
    regexp: "{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
  - key: VARNISH_LISTEN_ADDRESS
    value: "{{ varnish4_listen }}"
  - key: VARNISH_LISTEN_PORT
    value: "{{ varnish4_port }}"
  notify:
  - restart varnish

# Push customer configuration
- name: push customer configuration
  template:
    src: "{{ varnish4_recv_dir }}/{{ item }}.vcl.j2"
    dest: "/etc/varnish/include/recv_{{ item }}.vcl"
  with_items: varnish4_recv_files
  notify:
  - reload varnish

# Push varnish default config
- name: push varnish conguration file
  template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
  notify:
  - reload varnish

# Start daemon
- name: start varnish
  service: name=varnish state=started enabled=yes

# Push varnish utilities
- name: push varnish utilities
  copy:
    dest: "/usr/local/bin/{{ item }}"
    src: "{{ item }}"
    mode: 755
  with_items:
  - varnish_purge_all
  - varnish_purge_url
  - varnish_purge_vhost


