---
# defaults file for varnish4
#


# Where to find customer configuration, can be relative to the role, or another
# absolute directory
varnish4_recv_dir: include

# Define custom customer configuration files (list)
varnish4_recv_files: []


# Leave empty if you want varnish to listen all interfaces
varnish4_listen:

# Define the HTTP listening port
varnish4_port: 80

# Define a list of IP where debug information can be shown
varnish4_acl_debug:
- 208.88.110.46
- 70.30.197.38
- 127.0.0.1

# Define varnish HTTP backends
varnish4_backends:
  default:
    type: backend
    host: 10.0.42.21
    port: 80
  web1:
    type: backend
    host: 10.0.42.21
    probe: /index.html
    port: 80
  web2:
    type: backend
    host: 10.0.42.22
    probe: /index.html
    port: 80
  web:
    type: director
    backends:
    - web1
    - web2



